window.MOCK_BECE = {
  'Mathematics': {
    time: '2 Hours',
    instructions: 'Answer all questions in Section A. Answer any 4 questions from Section B. All workings must be clearly shown in Section B to earn full marks. Calculators are permitted.',
    sectionA: [
      {q: "Find the value of x if 2x - 5 = 11.", o: ["3", "6", "8", "16"], a: 2},
      {q: "What is the lowest common multiple (LCM) of 8 and 12?", o: ["24", "48", "96", "4"], a: 0},
      {q: "Simplify: 3a + 4b - a + 2b", o: ["2a + 6b", "4a + 6b", "2a - 2b", "4a - 2b"], a: 0},
      {q: "Find the perimeter of a rectangle with length 15cm and width 8cm.", o: ["23cm", "46cm", "120cm", "30cm"], a: 1},
      {q: "Express 75% as a fraction in its lowest terms.", o: ["3/4", "1/4", "2/3", "4/5"], a: 0},
      {q: "If the mean of 4, x, 8, and 10 is 7, find the value of x.", o: ["5", "6", "7", "8"], a: 1},
      {q: "Calculate the simple interest on Le 50,000 for 2 years at 5% per annum.", o: ["Le 2,500", "Le 5,000", "Le 7,500", "Le 10,000"], a: 1},
      {q: "Which of the following is a prime number?", o: ["9", "15", "21", "29"], a: 3},
      {q: "Evaluate: (-4) x (-3) + 5", o: ["17", "-7", "7", "-17"], a: 0},
      {q: "Solve the inequality: 3y > 12", o: ["y > 4", "y < 4", "y = 4", "y > -4"], a: 0},
      {q: "What is the square root of 144?", o: ["10", "12", "14", "16"], a: 1},
      {q: "Find the area of a triangle with base 10cm and height 8cm.", o: ["40 sq cm", "80 sq cm", "20 sq cm", "18 sq cm"], a: 0},
      {q: "Express 0.045 as a percentage.", o: ["4.5%", "45%", "0.45%", "450%"], a: 0},
      {q: "If a set A = {2, 4, 6, 8}, how many subsets does it have?", o: ["8", "12", "16", "32"], a: 2},
      {q: "Find the median of the following numbers: 2, 8, 4, 10, 6.", o: ["4", "6", "8", "10"], a: 1},
      {q: "A boy buys a shirt for Le 20,000 and sells it for Le 25,000. Calculate his percentage profit.", o: ["20%", "25%", "15%", "30%"], a: 1},
      {q: "Evaluate 3² + 4²", o: ["7", "14", "25", "49"], a: 2},
      {q: "The sum of interior angles of a triangle is:", o: ["90°", "180°", "270°", "360°"], a: 1},
      {q: "Simplify: a⁵ / a²", o: ["a³", "a⁷", "a²", "a¹⁰"], a: 0},
      {q: "Find the circumference of a circle with radius 7cm (Take π = 22/7).", o: ["22cm", "44cm", "154cm", "88cm"], a: 1},
      {q: "A train travels 120km in 2 hours. What is its average speed?", o: ["50 km/h", "60 km/h", "70 km/h", "80 km/h"], a: 1},
      {q: "Write 1,250,000 in standard form.", o: ["1.25 x 10⁵", "1.25 x 10⁶", "12.5 x 10⁵", "125 x 10⁴"], a: 1},
      {q: "What is the probability of rolling a 3 on a fair six-sided die?", o: ["1/2", "1/3", "1/6", "3/6"], a: 2},
      {q: "If x = 3 and y = -2, evaluate 2x + 3y.", o: ["0", "6", "-6", "12"], a: 0},
      {q: "Find the Highest Common Factor (HCF) of 18 and 24.", o: ["2", "3", "4", "6"], a: 3},
      {q: "Which angle is an obtuse angle?", o: ["45°", "90°", "120°", "180°"], a: 2},
      {q: "Simplify the fraction 18/24 to its lowest terms.", o: ["2/3", "3/4", "4/5", "6/8"], a: 1},
      {q: "A polygon with 5 sides is called a:", o: ["Hexagon", "Pentagon", "Octagon", "Quadrilateral"], a: 1},
      {q: "Find the value of y if y/4 = 8.", o: ["2", "12", "24", "32"], a: 3},
      {q: "How many degrees are in a full circle?", o: ["90°", "180°", "270°", "360°"], a: 3}
    ],
    sectionB: [
      "1. (a) Solve the simultaneous equations: 2x + y = 7 and x - y = 2. (b) Find the area of a circle with diameter 14cm (Take π = 22/7).",
      "2. A man earns Le 150,000 a month. He spends 20% on rent, 30% on food, and saves the rest. (a) How much does he spend on rent? (b) How much does he save?",
      "3. The marks scored by 10 students in a test are: 5, 8, 4, 7, 6, 8, 9, 3, 5, 8. Find the: (a) Mode, (b) Median, (c) Mean.",
      "4. (a) Simplify: (3x²y) × (2xy³). (b) Factorize completely: 2x² - 8.",
      "5. Construct a triangle ABC where AB = 6cm, BC = 8cm and angle ABC = 90°. Measure and state the length of AC."
    ]
  },
  'English Language': {
    time: '2 Hours 15 Minutes',
    instructions: 'Answer all questions in Section A (Lexis and Structure). In Section B, answer the comprehension question and write one essay from the given topics.',
    sectionA: [
      {q: "Choose the word that correctly completes the sentence: The teacher ____ the students to read daily.", o: ["adviced", "advised", "advises", "advicing"], a: 1},
      {q: "Which of the following sentences is grammatically correct?", o: ["He has went home.", "He have gone home.", "He has gone home.", "He is gone home."], a: 2},
      {q: "Identify the figure of speech: 'The wind whistled through the trees.'", o: ["Simile", "Metaphor", "Personification", "Hyperbole"], a: 2},
      {q: "Choose the synonym for 'Abundant'.", o: ["Scarce", "Plentiful", "Rare", "Empty"], a: 1},
      {q: "Choose the antonym for 'Barren'.", o: ["Empty", "Fertile", "Dry", "Harsh"], a: 1},
      {q: "Fill in the blank: She is good ____ mathematics.", o: ["in", "at", "with", "on"], a: 1},
      {q: "What is the plural of 'Phenomenon'?", o: ["Phenomenons", "Phenomena", "Phenomenones", "Phenomas"], a: 1},
      {q: "Choose the correctly spelt word.", o: ["Accomodation", "Accommodation", "Acommodation", "Acomodation"], a: 1},
      {q: "The boy ____ bag was stolen is crying.", o: ["who", "whom", "whose", "which"], a: 2},
      {q: "Neither John nor his friends ____ present yesterday.", o: ["was", "were", "is", "are"], a: 1},
      {q: "Identify the adverb in: 'She sang beautifully at the concert.'", o: ["She", "sang", "beautifully", "concert"], a: 2},
      {q: "A story of a person's life written by someone else is called a/an:", o: ["Autobiography", "Biography", "Novel", "Memoir"], a: 1},
      {q: "Complete the proverb: A stitch in time saves ____.", o: ["nine", "time", "mine", "money"], a: 0},
      {q: "Fill in the blank: He prefers reading ____ playing football.", o: ["than", "to", "over", "from"], a: 1},
      {q: "Which word rhymes with 'Rough'?", o: ["Bough", "Through", "Tough", "Cough"], a: 2},
      {q: "The prefix 'un-' in 'unhappy' means:", o: ["Again", "Not", "Before", "After"], a: 1},
      {q: "Identify the preposition: 'The cat is hiding under the bed.'", o: ["cat", "hiding", "under", "bed"], a: 2},
      {q: "What is the past participle of 'Drink'?", o: ["Drank", "Drunk", "Drinked", "Drinking"], a: 1},
      {q: "We have lived here ____ 2010.", o: ["since", "for", "from", "until"], a: 0},
      {q: "I am looking forward to ____ you.", o: ["see", "saw", "seeing", "seen"], a: 2},
      {q: "Choose the correctly punctuated sentence.", o: ["Its a beautiful day.", "It's a beautiful day.", "Its' a beautiful day.", "It is a beautiful, day."], a: 1},
      {q: "He is the ____ boy in the class.", o: ["tall", "taller", "tallest", "most tall"], a: 2},
      {q: "A group of lions is called a:", o: ["Flock", "Herd", "Pride", "Swarm"], a: 2},
      {q: "Choose the word opposite in meaning to 'Poverty'.", o: ["Wealth", "Sadness", "Poor", "Sickness"], a: 0},
      {q: "If I ____ a bird, I would fly.", o: ["was", "were", "am", "be"], a: 1},
      {q: "The man died ____ Malaria.", o: ["of", "from", "with", "by"], a: 0},
      {q: "Which of the following is a compound word?", o: ["Happiness", "Sunlight", "Running", "Beautiful"], a: 1},
      {q: "An animal that eats both plants and meat is called an:", o: ["Herbivore", "Carnivore", "Omnivore", "Insectivore"], a: 2},
      {q: "Identify the conjunction: 'I wanted to go, but it rained.'", o: ["wanted", "to", "but", "rained"], a: 2},
      {q: "Fill in the blank: You must abide ____ the rules.", o: ["with", "by", "on", "in"], a: 1}
    ],
    sectionB: [
      "1. Comprehension: Read the passage provided by your invigilator and answer the five questions below based on it. (a) What is the main idea of the passage? (b) Why did the protagonist leave the village? (c) Explain the meaning of the word 'resilient' as used in the passage. (d) What was the turning point in the story? (e) Give a suitable title for the passage.",
      "2. Essay: Write a letter to your friend in another town, telling them about your preparation for the BECE.",
      "3. Essay: Write an essay on the topic 'The Importance of Agriculture in Sierra Leone'.",
      "4. Essay: Write a story ending with the words: '...and I promised myself never to tell a lie again.'",
      "5. Essay: Describe a memorable event that took place in your school recently."
    ]
  },
  'Integrated Science': {
    time: '2 Hours',
    instructions: 'Answer all questions in Section A. Answer any 4 questions from Section B.',
    sectionA: [
      {q: "Which of the following is not a state of matter?", o: ["Solid", "Liquid", "Gas", "Energy"], a: 3},
      {q: "The process by which plants make their own food is called:", o: ["Respiration", "Photosynthesis", "Transpiration", "Digestion"], a: 1},
      {q: "What is the standard unit of force?", o: ["Joule", "Watt", "Newton", "Pascal"], a: 2},
      {q: "Which blood cells are responsible for fighting diseases?", o: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], a: 1},
      {q: "The chemical symbol for Sodium is:", o: ["S", "So", "Na", "N"], a: 2},
      {q: "Which instrument is used to measure atmospheric pressure?", o: ["Thermometer", "Barometer", "Anemometer", "Hygrometer"], a: 1},
      {q: "What is the main organ of the human respiratory system?", o: ["Heart", "Liver", "Lungs", "Kidney"], a: 2},
      {q: "The center of an atom is called the:", o: ["Electron", "Proton", "Nucleus", "Orbit"], a: 2},
      {q: "Which of these is a renewable source of energy?", o: ["Coal", "Petroleum", "Solar energy", "Natural gas"], a: 2},
      {q: "Water boils at ____ degrees Celsius at sea level.", o: ["50", "90", "100", "120"], a: 2},
      {q: "Which planet is closest to the Sun?", o: ["Venus", "Earth", "Mars", "Mercury"], a: 3},
      {q: "The breakdown of food into simpler substances is called:", o: ["Excretion", "Digestion", "Respiration", "Circulation"], a: 1},
      {q: "A substance with a pH of 3 is:", o: ["Acidic", "Neutral", "Basic", "Alkaline"], a: 0},
      {q: "Which vitamin is primarily obtained from sunlight?", o: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], a: 3},
      {q: "The green pigment in plants is called:", o: ["Chloroplast", "Chlorophyll", "Stomata", "Melanin"], a: 1},
      {q: "An object at rest stays at rest due to:", o: ["Friction", "Gravity", "Inertia", "Momentum"], a: 2},
      {q: "Which of the following diseases is caused by a virus?", o: ["Malaria", "Cholera", "HIV/AIDS", "Tuberculosis"], a: 2},
      {q: "The part of the eye that controls the amount of light entering is the:", o: ["Lens", "Retina", "Iris", "Cornea"], a: 2},
      {q: "Sound cannot travel through a:", o: ["Solid", "Liquid", "Gas", "Vacuum"], a: 3},
      {q: "What type of simple machine is a seesaw?", o: ["Pulley", "Lever", "Inclined plane", "Wheel and axle"], a: 1},
      {q: "The hardest naturally occurring substance on Earth is:", o: ["Gold", "Iron", "Diamond", "Quartz"], a: 2},
      {q: "Animals that live both on land and in water are called:", o: ["Mammals", "Reptiles", "Amphibians", "Birds"], a: 2},
      {q: "Electric current is measured in:", o: ["Volts", "Watts", "Ohms", "Amperes"], a: 3},
      {q: "The male reproductive part of a flower is the:", o: ["Stigma", "Style", "Ovary", "Stamen"], a: 3},
      {q: "Which process involves the change of state from gas to liquid?", o: ["Evaporation", "Condensation", "Sublimation", "Melting"], a: 1},
      {q: "What is the chemical formula for carbon dioxide?", o: ["CO", "CO2", "C2O", "C2O2"], a: 1},
      {q: "The main function of the human skeleton is to:", o: ["Digest food", "Pump blood", "Support and protect the body", "Produce hormones"], a: 2},
      {q: "Which part of the cell controls all its activities?", o: ["Cytoplasm", "Cell wall", "Nucleus", "Vacuole"], a: 2},
      {q: "Rusting of iron is an example of:", o: ["Physical change", "Chemical change", "Biological change", "Nuclear change"], a: 1},
      {q: "The unit of work is the:", o: ["Joule", "Newton", "Watt", "Pascal"], a: 0}
    ],
    sectionB: [
      "1. (a) Define photosynthesis. (b) Write the word equation for photosynthesis. (c) State three factors necessary for photosynthesis to occur.",
      "2. (a) What is a mixture? (b) List three methods used for separating mixtures. (c) Explain how you would separate a mixture of sand and salt.",
      "3. (a) State Newton's first law of motion. (b) Define friction. (c) Give two advantages and two disadvantages of friction.",
      "4. (a) Name the three main types of blood vessels in the human body. (b) Explain the function of red blood cells. (c) What is the difference between an artery and a vein?",
      "5. (a) Define an element and give two examples. (b) What are the three subatomic particles found in an atom? (c) State their electrical charges."
    ]
  },
  'Social Studies': {
    time: '2 Hours',
    instructions: 'Answer all objective questions. In Section B, answer four questions, ensuring you cover different thematic areas.',
    sectionA: [
      {q: "The highest mountain in Sierra Leone is:", o: ["Mount Everest", "Loma Mountains (Mount Bintumani)", "Tingi Mountains", "Sugar Loaf"], a: 1},
      {q: "Who is the head of the executive branch of government in Sierra Leone?", o: ["The Chief Justice", "The Speaker of Parliament", "The President", "The Mayor"], a: 2},
      {q: "Sierra Leone gained independence from British rule in what year?", o: ["1957", "1960", "1961", "1965"], a: 2},
      {q: "Which of the following is a fundamental human right?", o: ["Right to steal", "Right to life", "Right to avoid taxes", "Right to discriminate"], a: 1},
      {q: "The process of counting people in a country is called:", o: ["Voting", "Election", "Census", "Registration"], a: 2},
      {q: "The official language of Sierra Leone is:", o: ["Krio", "Mende", "Temne", "English"], a: 3},
      {q: "Which physical feature separates Africa from Europe?", o: ["The Red Sea", "The Mediterranean Sea", "The Atlantic Ocean", "The Sahara Desert"], a: 1},
      {q: "A system of government where power is vested in the people is called:", o: ["Monarchy", "Dictatorship", "Democracy", "Oligarchy"], a: 2},
      {q: "The movement of people from rural to urban areas is known as:", o: ["Migration", "Urbanization", "Colonization", "Deforestation"], a: 1},
      {q: "Which organization was established to promote unity among African nations?", o: ["UN", "ECOWAS", "AU (African Union)", "WHO"], a: 2},
      {q: "The currency used in Sierra Leone is the:", o: ["Dollar", "Pound", "Cedi", "Leone"], a: 3},
      {q: "The longest river in Africa is the:", o: ["River Niger", "River Congo", "River Nile", "River Zambezi"], a: 2},
      {q: "What does the green color on the Sierra Leone flag represent?", o: ["Peace", "Agriculture and Mountains", "The Ocean", "Mineral Wealth"], a: 1},
      {q: "Which of these is a primary sector economic activity?", o: ["Teaching", "Banking", "Farming", "Manufacturing"], a: 2},
      {q: "The first Prime Minister of independent Sierra Leone was:", o: ["Siaka Stevens", "Sir Milton Margai", "Albert Margai", "Ahmad Tejan Kabbah"], a: 1},
      {q: "What is the capital of the Southern Province in Sierra Leone?", o: ["Makeni", "Kenema", "Bo", "Port Loko"], a: 2},
      {q: "An area of land surrounded by water on all sides is called an:", o: ["Island", "Peninsula", "Isthmus", "Archipelago"], a: 0},
      {q: "Which arm of government is responsible for making laws?", o: ["Executive", "Judiciary", "Legislature", "Military"], a: 2},
      {q: "A family consisting of a father, mother, and their children is a:", o: ["Extended family", "Nuclear family", "Single-parent family", "Polygamous family"], a: 1},
      {q: "Which of these is a major cause of deforestation?", o: ["Planting trees", "Logging for timber", "Recycling paper", "Using solar energy"], a: 1},
      {q: "The global organization responsible for public health is:", o: ["UNICEF", "WHO", "UNESCO", "IMF"], a: 1},
      {q: "A natural resource found abundantly in Sierra Leone is:", o: ["Oil", "Diamonds", "Uranium", "Coal"], a: 1},
      {q: "The equator passes through which continent?", o: ["Europe", "North America", "Africa", "Antarctica"], a: 2},
      {q: "Who interprets the laws in a democratic state?", o: ["The Police", "The Legislature", "The Judiciary", "The President"], a: 2},
      {q: "Which of the following is a non-renewable resource?", o: ["Wind", "Water", "Petroleum", "Sunlight"], a: 2},
      {q: "The practice of growing crops and rearing animals is called:", o: ["Mining", "Agriculture", "Fishing", "Forestry"], a: 1},
      {q: "Which West African country shares a border with Sierra Leone to the north and east?", o: ["Liberia", "Ghana", "Guinea", "Mali"], a: 2},
      {q: "A map scale helps to:", o: ["Show the color of rivers", "Measure distance on the map relative to the ground", "Tell the time", "Identify countries"], a: 1},
      {q: "What is the primary purpose of taxation?", o: ["To punish citizens", "To generate revenue for the government", "To reduce population", "To support foreign countries"], a: 1},
      {q: "The process of socializing a child begins in the:", o: ["School", "Church/Mosque", "Family", "Community"], a: 2}
    ],
    sectionB: [
      "1. (a) Define culture. (b) Identify three elements of culture in Sierra Leone. (c) Explain two ways in which culture is transmitted from one generation to another.",
      "2. (a) What is rural-urban migration? (b) State three causes of rural-urban migration. (c) Explain two effects of this migration on urban areas.",
      "3. (a) Name the three arms of government in Sierra Leone. (b) Explain the primary function of each arm. (c) What is the importance of the separation of powers?",
      "4. (a) Define a natural resource. (b) List three mineral resources mined in Sierra Leone. (c) Discuss two ways mining impacts the environment.",
      "5. (a) What is an election? (b) State three qualities of a free and fair election. (c) Why is it important for citizens to vote?"
    ]
  },
  'ICT': {
    time: '2 Hours',
    instructions: 'Answer all questions in Section A. Answer 4 questions from Section B.',
    sectionA: [
      {q: "What does ICT stand for?", o: ["Information and Communication Technology", "Internal Computer Technology", "Internet and Computer Tools", "Information Center Technology"], a: 0},
      {q: "Which of the following is an input device?", o: ["Monitor", "Printer", "Keyboard", "Speaker"], a: 2},
      {q: "The 'Brain' of the computer is the:", o: ["RAM", "Hard Drive", "CPU", "Motherboard"], a: 2},
      {q: "Which software is used for word processing?", o: ["Microsoft Excel", "Microsoft Word", "Microsoft PowerPoint", "Adobe Photoshop"], a: 1},
      {q: "A global network connecting millions of computers is the:", o: ["Intranet", "Internet", "LAN", "WAN"], a: 1},
      {q: "What is the function of the RAM?", o: ["Permanent storage", "Temporary storage during processing", "Power supply", "Display output"], a: 1},
      {q: "Which of these is a search engine?", o: ["Windows", "Google", "Microsoft Office", "Firefox"], a: 1},
      {q: "A malicious program designed to harm a computer is called a:", o: ["Utility", "Browser", "Virus", "Firewall"], a: 2},
      {q: "Which of the following file extensions is used for a picture?", o: [".doc", ".xls", ".jpg", ".txt"], a: 2},
      {q: "To copy text, the keyboard shortcut is:", o: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + P"], a: 0},
      {q: "To paste text, the keyboard shortcut is:", o: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + P"], a: 1},
      {q: "An example of an output device is a:", o: ["Mouse", "Scanner", "Microphone", "Monitor"], a: 3},
      {q: "Which of these is not an operating system?", o: ["Windows 10", "Linux", "Microsoft Office", "macOS"], a: 2},
      {q: "The physical parts of a computer are called:", o: ["Software", "Malware", "Hardware", "Firmware"], a: 2},
      {q: "What does WWW stand for?", o: ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"], a: 0},
      {q: "A folder inside another folder is called a:", o: ["Subfolder", "File", "Directory", "Document"], a: 0},
      {q: "The blinking line that indicates where text will be entered is the:", o: ["Mouse", "Pointer", "Cursor", "Icon"], a: 2},
      {q: "Which program is best suited for creating financial budgets?", o: ["Microsoft Word", "Microsoft Excel", "CorelDraw", "Notepad"], a: 1},
      {q: "To save a new document, you click on:", o: ["Save As", "Print", "Open", "New"], a: 0},
      {q: "A gigabyte (GB) is equal to:", o: ["1024 Bytes", "1024 Kilobytes (KB)", "1024 Megabytes (MB)", "1024 Terabytes (TB)"], a: 2},
      {q: "What is the primary purpose of a firewall?", o: ["To cool down the computer", "To block unauthorized network access", "To speed up processing", "To store data"], a: 1},
      {q: "Which of these is a web browser?", o: ["Yahoo", "Bing", "Google Chrome", "Windows"], a: 2},
      {q: "When a computer is turned off, data stored in the ____ is lost.", o: ["Hard Disk", "ROM", "RAM", "Flash Drive"], a: 2},
      {q: "Sending an unsolicited bulk email is known as:", o: ["Phishing", "Hacking", "Spamming", "Surfing"], a: 2},
      {q: "Which device allows a computer to connect to the internet?", o: ["Monitor", "Modem/Router", "Printer", "Keyboard"], a: 1},
      {q: "A small picture on the desktop that represents a program is an:", o: ["Image", "Icon", "Graphic", "Avatar"], a: 1},
      {q: "What does CPU stand for?", o: ["Central Processing Unit", "Computer Personal Unit", "Central Print Unit", "Control Processing Unit"], a: 0},
      {q: "Which feature in MS Word is used to correct spelling automatically?", o: ["AutoFormat", "AutoCorrect", "SpellCheck", "WordArt"], a: 1},
      {q: "The intersection of a row and a column in a spreadsheet is a:", o: ["Block", "Grid", "Cell", "Table"], a: 2},
      {q: "Deleting a file moves it to the:", o: ["Desktop", "Recycle Bin", "Control Panel", "Documents folder"], a: 1}
    ],
    sectionB: [
      "1. (a) Define a computer system. (b) Differentiate between hardware and software, giving two examples of each.",
      "2. (a) What is an input device? (b) List three input devices and state their specific functions.",
      "3. (a) Explain the difference between RAM and ROM. (b) Why is secondary storage necessary in a computer?",
      "4. (a) What is the Internet? (b) List three uses of the Internet for a student. (c) State two dangers associated with using the Internet.",
      "5. (a) Explain what word processing software is used for. (b) Describe the function of the following shortcut keys: Ctrl+Z, Ctrl+S, Ctrl+A."
    ]
  }
};
